nodeLinker: node-modules

compressionLevel: 0

enableGlobalCache: true

enableImmutableInstalls: true

enableInlineBuilds: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

npmRegistryServer: "https://registry.npmjs.org/"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
